---
author: Gene Leynes
date: '2021-09-21'
title: Historical Community Area Diversity Index Maps
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r, message=FALSE, echo=FALSE, results='hide'}

## Libraries
library(geneorama)
library(shiny)
library(leaflet)
library(RColorBrewer)
library(rgdal)
library(rgeos)
library(sp)
library(data.table)
library(colorspace)
library(raster)

## Note: stadia is not rendering online, so the key isn't necessary. 
## API Key for stadia
# leaflet_stadia_url <- "https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}{r}.png?apikey={'%s'}" %>% sprintf(., yaml::read_yaml("config/stadia.yaml"))
# leaflet_stadia_attribution <- '&copy; <a href="https://stadiamaps.com/">Stadia Maps</a>, &copy; <a href="https://openmaptiles.org/">OpenMapTiles</a> &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors'

sourceDir("R/functions/")
```



```{r, message=FALSE, echo=FALSE, results='hide'}

# LOAD TRACT LEVEL DEMOGRAPHIC DATA

##------------------------------------------------------------------------------
## DEMOGRAPHIC DATA
##------------------------------------------------------------------------------

## READ IN FROM SOURCE
pl_2000_tract <- "data/pl_2000_il_tract.csv" %>% 
    fread_census %>% di_race_var_table %>% .[,DI:=diversity_index(.)] %>% 
    .[COUNTY=="031"]
pl_2010_tract <- "data/pl_2010_il_tract.csv" %>% 
    fread_census %>% di_race_var_table %>% .[,DI:=diversity_index(.)] %>% 
    .[COUNTY=="031"]
pl_2020_tract <- "data/il2020.pl_COMBINED_TRACT.csv" %>% 
    fread_census %>% di_race_var_table %>% .[,DI:=diversity_index(.)] %>% 
    .[COUNTY=="031"]

pl_2000_tract
pl_2010_tract
pl_2020_tract

```


```{r, message=FALSE, echo=FALSE, results='hide'}

## LOAD TRACT SHAPEFILES, JUST FOR THE COMMUNITY AREA MAPPING

##------------------------------------------------------------------------------
## SHAPEFILES
##------------------------------------------------------------------------------
shp_tracts_2000 <- readOGR("data/tl_2010_17031_tract00")
shp_tracts_2010 <- readOGR("data/tl_2010_17031_tract10")
shp_tracts_2020 <- readOGR("data/tl_2020_17031_tract20")

##==============================================================================
## COMMUNITY AREA DATA / GEOCODING
##==============================================================================
data("chi_community_areas")

## Generate city outline
chi_city_outline <- rgeos::gUnaryUnion(as(chi_community_areas, "SpatialPolygons"))


shp_tracts_2000$community <- geocode_to_map(lat = shp_tracts_2000$INTPTLAT00, 
                                            lon = shp_tracts_2000$INTPTLON00,
                                            map = chi_community_areas,
                                            "community")
shp_tracts_2010$community <- geocode_to_map(lat = shp_tracts_2010$INTPTLAT10, 
                                            lon = shp_tracts_2010$INTPTLON10,
                                            map = chi_community_areas,
                                            "community")
shp_tracts_2020$community <- geocode_to_map(lat = shp_tracts_2020$INTPTLAT20, 
                                            lon = shp_tracts_2020$INTPTLON20,
                                            map = chi_community_areas,
                                            "community")

shp_tracts_2000$chicago <- !is.na(shp_tracts_2000@data$community)
shp_tracts_2010$chicago <- !is.na(shp_tracts_2010@data$community)
shp_tracts_2020$chicago <- !is.na(shp_tracts_2020@data$community)


inin(pl_2000_tract$GEO_ID, shp_tracts_2000$CTIDFP00)
inin(pl_2010_tract$GEO_ID, shp_tracts_2010$GEOID10)
inin(pl_2020_tract$GEO_ID, shp_tracts_2020$GEOID20)

setnames(shp_tracts_2000@data,"CTIDFP00", "GEO_ID")
setnames(shp_tracts_2010@data,"GEOID10", "GEO_ID")
setnames(shp_tracts_2020@data,"GEOID20", "GEO_ID")
```

```{r, message=FALSE, echo=FALSE, results='hide'}

## MERGE TRACT / CA MAPPING INTO DATA TABLES

pl_2000_ca <- merge(pl_2000_tract[,-c("STATE", "COUNTY", "TRACT", "LSAD_NAME", "DI")],
                    shp_tracts_2000@data %>% data.table %>% .[,list(GEO_ID, community, chicago)],
                    by = "GEO_ID", sort = FALSE)
pl_2010_ca <- merge(pl_2010_tract[,-c("STATE", "COUNTY", "TRACT", "LSAD_NAME", "DI")],
                    shp_tracts_2010@data %>% data.table %>% .[,list(GEO_ID, community, chicago)],
                    by = "GEO_ID", sort = FALSE)
pl_2020_ca <- merge(pl_2020_tract[,-c("STATE", "COUNTY", "TRACT", "LSAD_NAME", "DI")],
                    shp_tracts_2020@data %>% data.table %>% .[,list(GEO_ID, community, chicago)],
                    by = "GEO_ID", sort = FALSE)


## AGGREGATE TO CA

pl_2000_ca <- pl_2000_ca[i = TRUE, 
                         lapply(.SD, sum), 
                         .SDcols = c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI", "SOR", "MULTI"),
                         keyby = list(community, chicago)]
pl_2010_ca <- pl_2010_ca[i = TRUE, 
                         lapply(.SD, sum), 
                         .SDcols = c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI", "SOR", "MULTI"),
                         keyby = list(community, chicago)]
pl_2020_ca <- pl_2020_ca[i = TRUE, 
                         lapply(.SD, sum), 
                         .SDcols = c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI", "SOR", "MULTI"),
                         keyby = list(community, chicago)]

pl_2000_ca$DI <- pl_2000_ca %>% diversity_index
pl_2010_ca$DI <- pl_2010_ca %>% diversity_index
pl_2020_ca$DI <- pl_2020_ca %>% diversity_index
```


```{r, message=FALSE, echo=FALSE, results='hide'}
## SUMMARIZE COMMUNITY AREAS BY YEAR

ca_di_summary <- Reduce(function(x, y) merge(x,y, 
                            by = c("community", "chicago")),
       list(pl_2000_ca, pl_2010_ca, pl_2020_ca))
setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "\\.x$", "_2000"))
setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "\\.y$", "_2010"))

setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "^TOT$", "TOT_2020"))
setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "^H$", "H_2020"))
setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "^W$", "W_2020"))
setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "^B$", "B_2020"))
setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "^AIAN$", "AIAN_2020"))
setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "^ASIAN$", "ASIAN_2020"))
setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "^NHPI$", "NHPI_2020"))
setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "^SOR$", "SOR_2020"))
setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "^MULTI$", "MULTI_2020"))
setnames(ca_di_summary, gsub(x = colnames(ca_di_summary), "^DI$", "DI_2020"))
```



```{r, message=FALSE, echo=FALSE, results='hide'}

shp_tracts_2020@data %>% head

chi_community_areas@data <- merge(chi_community_areas@data,
                                  ca_di_summary,
                                  by = "community", sort = FALSE)

chi_community_areas@data %>% head

chi_community_areas$area <- area(chi_community_areas)

# ##==============================================================================
# ## ADD NORMALIZED VALUES TO SHAPE DATA 
# ## NORMALIZED BY PERCENT OF TOTAL
# ## NORMALIZED BY LAND MASS
# ##==============================================================================
# 
# chi_community_areas@data <- cbind(
#     chi_community_areas@data,
#     normalize_vars(chi_community_areas@data,
#                    c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI","SOR", "MULTI"),
#                    "TOT") %>% setnames(.,colnames(.) %>% tolower %>% paste0(., "_pct")),
#     normalize_vars(chi_community_areas@data,
#                    c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI","SOR", "MULTI"),
#                    "area") %>% setnames(.,colnames(.) %>% tolower %>% paste0(., "_dens")))
# 
# # shp_tracts_2010@data$ALAND10 <- shp_tracts_2010@data$ALAND10 %>% as.numeric
# shp_tracts_2010@data <- cbind(
#     shp_tracts_2010@data,
#     normalize_vars(shp_tracts_2010@data,
#                    c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI","SOR", "MULTI"),
#                    "TOT") %>% setnames(.,colnames(.) %>% tolower %>% paste0(., "_pct")),
#     normalize_vars(shp_tracts_2010@data,
#                    c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI","SOR", "MULTI"),
#                    "area") %>% setnames(.,colnames(.) %>% tolower %>% paste0(., "_dens")))
# 
# # shp_tracts_2020@data$ALAND20 <- shp_tracts_2020@data$ALAND20 %>% as.numeric
# shp_tracts_2020@data <- cbind(
#     shp_tracts_2020@data,
#     normalize_vars(shp_tracts_2020@data,
#                    c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI","SOR", "MULTI"),
#                    "TOT") %>% setnames(.,colnames(.) %>% tolower %>% paste0(., "_pct")),
#     normalize_vars(shp_tracts_2020@data,
#                    c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI","SOR", "MULTI"),
#                    "area") %>% setnames(.,colnames(.) %>% tolower %>% paste0(., "_dens")))
```


# Historical Diversity Index for 2000, 2010, and 2020

These histograms show the shift of the diversity index in Chicago over time. Over the past 20 years more community areas have more diversity.

```{r, echo=FALSE}
par(mfrow=c(1,3))
brks <- seq(0,1,.1)
hist(ca_di_summary$DI_2000, main = "Diversity index based on \n2000 Census", 
     breaks=brks, freq=!FALSE, ylim=c(0,20), ylab="", xlab="decile")
hist(ca_di_summary$DI_2010, main = "Diversity index based on \n2010 Census", 
     breaks=brks, freq=!FALSE, ylim=c(0,20), ylab="", xlab="decile")
hist(ca_di_summary$DI_2020, main = "Diversity index based on \n2020 Census", 
     breaks=brks, freq=!FALSE, ylim=c(0,20), ylab="", xlab="decile")
par(mfrow=c(1,1))
```

# Historical Diversity Index Maps for 2000, 2010, and 2020

The maps between the years look very similar, but some areas that have changed. The scale is held constant for comparison. 

```{r, echo=FALSE}
pal <- viridisLite::viridis(256, option = "D") %>%
    colorNumeric(palette = .,
                 domain = c(0,1),
                 na.color = "black", alpha = F, reverse = TRUE)
leaflet(chi_community_areas) %>%
    addProviderTiles("CartoDB.DarkMatter") %>%
    # addTiles(urlTemplate = leaflet_stadia_url,
    #          attribution = leaflet_stadia_attribution) %>%
    addPolygons(fillColor = ~pal(DI_2000),
                fillOpacity = 0.5,
                stroke=FALSE, weight = 0.5,
                label=~paste(community, DI_2000)) %>%
    addLegend(pal = pal,
              values = ~DI_2000,
              title = "Diversity Index 2000",
              position = "bottomright")

pal <- viridisLite::viridis(256, option = "D") %>%
    colorNumeric(palette = .,
                 domain = c(0,1),
                 na.color = "black", alpha = F, reverse = TRUE)
leaflet(chi_community_areas) %>%
    addProviderTiles("CartoDB.DarkMatter") %>%
    # addTiles(urlTemplate = leaflet_stadia_url,
    #          attribution = leaflet_stadia_attribution) %>%
    addPolygons(fillColor = ~pal(DI_2010),
                fillOpacity = 0.5,
                stroke=FALSE, weight = 0.5,
                label=~paste(community, DI_2010)) %>%
    addLegend(pal = pal,
              values = ~DI_2010,
              title = "Diversity Index 2010",
              position = "bottomright")

pal <- viridisLite::viridis(256, option = "D") %>%
    colorNumeric(palette = .,
                 domain = c(0,1),
                 na.color = "black", alpha = F, reverse = TRUE)
leaflet(chi_community_areas) %>%
    addProviderTiles("CartoDB.DarkMatter") %>%
    # addTiles(urlTemplate = leaflet_stadia_url,
    #          attribution = leaflet_stadia_attribution) %>%
    addPolygons(fillColor = ~pal(DI_2020),
                fillOpacity = 0.5,
                stroke=FALSE, weight = 0.5,
                label=~paste(community, DI_2020)) %>%
    addLegend(pal = pal,
              values = ~DI_2020,
              title = "Diversity Index 2020",
              position = "bottomright")
```


```{r, eval=FALSE, results='hide',echo=FALSE}

## Chicago's ratio of height to width
# bbox(chi_city_outline)["y",] %>% diff %>% unname/
#     bbox(chi_city_outline)["x",] %>% diff %>% unname
# About .91



r <- shp2raster(shp_tracts_2020, column="tot_dens",
                ncells=1000)
plot(r)

r00 <- shp2raster(shp_tracts_2000, column="tot_dens",
                ncells=1000)
plot(r)
plot(r00)
plot(r-r00)


# summary(shp_tracts_2000)
# 
# r00 <- raster(shp_tracts_2000)
# summary(r00)

str(shp_tracts_2020@data)


# r <- rasterize(shp_tracts_2020, 
#                raster(ncol=700, nrow=700),
#                ext=extent(shp_tracts_2020),
#                "tot_pct")
# shp_tracts_2020$ALAND20 %>% sort %>% head
# shp_tracts_2020$tot_dens %>% sort %>% tail
# shp_tracts_2020@data[which(shp_tracts_2020$ALAND20==0),]
# which(shp_tracts_2020$tot_dens==max(shp_tracts_2020$tot_dens, na.rm=T)) %>% shp_tracts_2020@data[.,]
# 
# library(raster)
# x <- shapefile('file.shp')
# crs(x)
# plot(area(shp_tracts_2020) %>% pmin(., 1e8) , shp_tracts_2020$ALAND20)
# hist(area(shp_tracts_2020) %>% .[.<3e7] )
# area(shp_tracts_2020) %>% sort %>% head
# 
# plot(r)
# 
# 
# 
# r <- raster(ncol=700, nrow=700)
# extent(r) <- extent(shp_tracts_2020)
# shp_tracts_2020$temp <- shp_tracts_2020$TOT / as.numeric(shp_tracts_2020$ALAND20)
# rp <- rasterize(shp_tracts_2020, r, 'temp')
# plot(rp)
# 

# # ??raster
# ??bkde2D
# kde <- bkde2D(dat[ , list(longitude, latitude)],
#               bandwidth=c(.0045, .0068), gridsize = c(100,100))
# # Create Raster from Kernel Density output
# KernelDensityRaster <- raster(list(x=kde$x1 ,y=kde$x2 ,z = kde$fhat))
# 
# #create pal function for coloring the raster
# palRaster <- colorNumeric("Spectral", domain = KernelDensityRaster@data@values)
# 
# ## Leaflet map with raster
# leaflet() %>% addTiles() %>% 
#     addRasterImage(KernelDensityRaster, 
#                    colors = palRaster, 
#                    opacity = .8) %>%
#     addLegend(pal = palRaster, 
#               values = KernelDensityRaster@data@values, 
#               title = "Kernel Density of Points")

```




