---
author: Gene Leynes
date: '2021-08-30'
title: Historical Tract Analysis
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r, message=FALSE, echo=FALSE, results='hide'}

## Libraries
library(geneorama)
library(shiny)
library(leaflet)
library(RColorBrewer)
library(rgdal)
library(rgeos)
library(sp)
library(data.table)
library(colorspace)
library(raster)

## API Key for stadia
leaflet_stadia_url <- "https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}{r}.png?apikey={'%s'}" %>% sprintf(., yaml::read_yaml("config/stadia.yaml"))
leaflet_stadia_attribution <- '&copy; <a href="https://stadiamaps.com/">Stadia Maps</a>, &copy; <a href="https://openmaptiles.org/">OpenMapTiles</a> &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors'

sourceDir("R/functions/")

##------------------------------------------------------------------------------
## DEMOGRAPHIC DATA
##------------------------------------------------------------------------------

## READ IN FROM SOURCE
pl_2010_block <- "data/pl_2010_cook_block.csv.gz" %>% 
    fread_census %>% di_race_var_table %>% .[,DI:=diversity_index(.)] %>%
    .[COUNTY=="031"]
pl_2020_block <- "data/il2020.pl_COMBINED_BLOCK.csv.gz" %>% 
    fread_census %>% di_race_var_table %>% .[,DI:=diversity_index(.)] %>% 
    .[COUNTY=="031"]

pl_2010_block[ , GEO_ID := gsub(".+US", "", GEO_ID)]
pl_2020_block[ , GEO_ID := gsub(".+US", "", GEO_ID)]

##------------------------------------------------------------------------------
## SHAPEFILES
##------------------------------------------------------------------------------

shp_block_2010 <- readOGR("data/tl_2020_17031_tabblock10")
shp_block_2020 <- readOGR("data/tl_2020_17031_tabblock20")

##==============================================================================
## COMMUNITY AREA DATA / GEOCODING
##==============================================================================
data("chi_community_areas")

## Generate city outline
chi_city_outline <- rgeos::gUnaryUnion(as(chi_community_areas, "SpatialPolygons"))


shp_block_2010$community <- geocode_to_map(lat = shp_block_2010$INTPTLAT10, 
                                           lon = shp_block_2010$INTPTLON10,
                                           map = chi_community_areas,
                                           "community")
shp_block_2020$community <- geocode_to_map(lat = shp_block_2020$INTPTLAT20, 
                                           lon = shp_block_2020$INTPTLON20,
                                           map = chi_community_areas,
                                           "community")

shp_block_2010$chicago <- !is.na(shp_block_2010@data$community)
shp_block_2020$chicago <- !is.na(shp_block_2020@data$community)


shp_block_2010@data %>% head
shp_block_2020@data %>% head

setnames(shp_block_2010@data, "GEOID10", "GEO_ID")
setnames(shp_block_2020@data, "GEOID20", "GEO_ID")

inin(shp_block_2010$GEO_ID, pl_2010_block$GEO_ID)
inin(shp_block_2020$GEO_ID, pl_2020_block$GEO_ID)

inin(shp_block_2010$GEO_ID, shp_block_2020$GEO_ID)
```

```{r}
shp_block_2010$area <- area(shp_block_2010)
shp_block_2020$area <- area(shp_block_2020)

shp_block_2010@data <- merge(shp_block_2010@data,
                              pl_2010_block,
                              by = "GEO_ID", sort = FALSE)
shp_block_2020@data <- merge(shp_block_2020@data,
                              pl_2020_block,
                              by = "GEO_ID", sort = FALSE)

shp_block_2010@data %>% head
shp_block_2020@data %>% head

shp_block_2010@data %>% as.data.table %>% .[chicago==TRUE, sum(TOT)]
shp_block_2020@data %>% as.data.table %>% .[chicago==TRUE, sum(TOT)]

shp_block_2010@data %>% as.data.table %>% .[, sum(TOT)]
shp_block_2020@data %>% as.data.table %>% .[, sum(TOT)]



##==============================================================================
## ADD NORMALIZED VALUES TO SHAPE DATA 
## NORMALIZED BY PERCENT OF TOTAL
## NORMALIZED BY LAND MASS
##==============================================================================

shp_block_2010@data <- cbind(
    shp_block_2010@data,
    normalize_vars(shp_block_2010@data,
                   c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI","SOR", "MULTI"),
                   "TOT") %>% setnames(.,colnames(.) %>% tolower %>% paste0(., "_pct")),
    normalize_vars(shp_block_2010@data,
                   c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI","SOR", "MULTI"),
                   "area") %>% setnames(.,colnames(.) %>% tolower %>% paste0(., "_dens")))

shp_block_2020@data <- cbind(
    shp_block_2020@data,
    normalize_vars(shp_block_2020@data,
                   c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI","SOR", "MULTI"),
                   "TOT") %>% setnames(.,colnames(.) %>% tolower %>% paste0(., "_pct")),
    normalize_vars(shp_block_2020@data,
                   c("TOT", "H", "W", "B", "AIAN", "ASIAN", "NHPI","SOR", "MULTI"),
                   "area") %>% setnames(.,colnames(.) %>% tolower %>% paste0(., "_dens")))

shp_block_2010@data %>% head
shp_block_2020@data %>% head


shp_block_2010@data %>% subset(chicago==TRUE) %>% .[,"TOT"] %>% sum
shp_block_2020@data %>% subset(chicago==TRUE) %>% .[,"TOT"] %>% sum
```


# Historical Diversity Index for 2000, 2010, and 2020

The histograms show how the amount of diversity in Chicago has increased over time. 

```{r, echo=FALSE}
par(mfrow=c(2,2))
shp_block_2010@data %>% subset(chicago==TRUE) %>% .[,"DI"] %>% hist
shp_block_2020@data %>% subset(chicago==TRUE) %>% .[,"DI"] %>% hist

hist(pl_2010_block$DI, main = "Diversity index based on 2010 Census")
hist(pl_2020_block$DI, main = "Diversity index based on 2020 Census")
par(mfrow=c(1,1))
```

# Historical Diversity Index Maps for 2010, and 2020

The maps between the years look very similar, but there are some area that have changed. 

```{r, echo=FALSE}
pal <- viridisLite::viridis(256, option = "D") %>%
    colorNumeric(palette = .,
                 domain = shp_block_2020$DI,
                 na.color = "black", alpha = F, reverse = TRUE)
leaflet(shp_block_2020[shp_block_2020$chicago==TRUE,]) %>%
    addTiles(urlTemplate = leaflet_stadia_url,
             attribution = leaflet_stadia_attribution) %>%
    addPolygons(fillColor = ~pal(DI),
                fillOpacity = 0.5,
                stroke=FALSE, weight = 0.5,
                label=~paste(GEO_ID, DI)) %>%
    addLegend(pal = pal,
              values = ~DI,
              title = "Diversity Index 2020",
              position = "bottomright")

pal <- viridisLite::viridis(256, option = "D") %>%
    colorNumeric(palette = .,
                 domain = shp_block_2010$DI,
                 na.color = "black", alpha = F, reverse = TRUE)
leaflet(shp_block_2010[shp_block_2010$chicago==TRUE,]) %>%
    addTiles(urlTemplate = leaflet_stadia_url,
             attribution = leaflet_stadia_attribution) %>%
    addPolygons(fillColor = ~pal(DI),
                fillOpacity = 0.5,
                stroke=FALSE, weight = 0.5,
                label=~paste(GEO_ID, DI)) %>%
    addLegend(pal = pal,
              values = ~DI,
              title = "Diversity Index 2010",
              position = "bottomright")
```


```{r, eval=FALSE, results='hide'}

## Chicago's ratio of height to width
# bbox(chi_city_outline)["y",] %>% diff %>% unname/
#     bbox(chi_city_outline)["x",] %>% diff %>% unname
# About .91



r <- shp2raster(shp_block_2020, column="tot_dens",
                ncells=1000)
plot(r)

r00 <- shp2raster(shp_tracts_2000, column="tot_dens",
                ncells=1000)
plot(r)
plot(r00)
plot(r-r00)


# summary(shp_tracts_2000)
# 
# r00 <- raster(shp_tracts_2000)
# summary(r00)

str(shp_block_2020@data)


# r <- rasterize(shp_block_2020, 
#                raster(ncol=700, nrow=700),
#                ext=extent(shp_block_2020),
#                "tot_pct")
# shp_block_2020$ALAND20 %>% sort %>% head
# shp_block_2020$tot_dens %>% sort %>% tail
# shp_block_2020@data[which(shp_block_2020$ALAND20==0),]
# which(shp_block_2020$tot_dens==max(shp_block_2020$tot_dens, na.rm=T)) %>% shp_block_2020@data[.,]
# 
# library(raster)
# x <- shapefile('file.shp')
# crs(x)
# plot(area(shp_block_2020) %>% pmin(., 1e8) , shp_block_2020$ALAND20)
# hist(area(shp_block_2020) %>% .[.<3e7] )
# area(shp_block_2020) %>% sort %>% head
# 
# plot(r)
# 
# 
# 
# r <- raster(ncol=700, nrow=700)
# extent(r) <- extent(shp_block_2020)
# shp_block_2020$temp <- shp_block_2020$TOT / as.numeric(shp_block_2020$ALAND20)
# rp <- rasterize(shp_block_2020, r, 'temp')
# plot(rp)
# 

# # ??raster
# ??bkde2D
# kde <- bkde2D(dat[ , list(longitude, latitude)],
#               bandwidth=c(.0045, .0068), gridsize = c(100,100))
# # Create Raster from Kernel Density output
# KernelDensityRaster <- raster(list(x=kde$x1 ,y=kde$x2 ,z = kde$fhat))
# 
# #create pal function for coloring the raster
# palRaster <- colorNumeric("Spectral", domain = KernelDensityRaster@data@values)
# 
# ## Leaflet map with raster
# leaflet() %>% addTiles() %>% 
#     addRasterImage(KernelDensityRaster, 
#                    colors = palRaster, 
#                    opacity = .8) %>%
#     addLegend(pal = palRaster, 
#               values = KernelDensityRaster@data@values, 
#               title = "Kernel Density of Points")

```




